# 사용 방법 : https://dart.dev/guides/language/analysis-options
# 규칙 : https://dart-lang.github.io/linter/lints/index.html.

# 좋은 코딩 방법을 권장하도록 설계된 Flutter 앱, 패키지 및 플러그인에 대한
# 권장 린트 세트를 활성화합니다 .
include: package:flutter_lints/flutter.yaml

# 규칙의 심각도 변경
# 경고 warning / 에러 error / 정보 info / 무시 ignore
analyzer:
  errors:
    avoid_print: warning

# 규칙 제외 파일
#  exclude:
#    - lib/client.dart
#    - lib/server/*.g.dart
#    - test/_data/**

# 규칙 추가 파일
linter:
  rules:
    - avoid_relative_lib_imports
    - avoid_types_as_parameter_names
    - no_duplicate_case_values
    - unrelated_type_equality_checks
    - valid_regexps